#!/usr/bin/env python3

import requests as r 
import json 
import argparse
import os
import webbrowser
import time
from time import sleep

import colorama
from colorama import Fore, Back, Style
colorama.init(autoreset=True)




def create_parser():

    #Creating a argument parser
    parser = argparse.ArgumentParser(description="Preguiça de acessar o crt.sh então eu criei isso pra pegar tudo de lá pra mim!")

    #argumento do domínio/link 
    parser.add_argument("-d","--domain",type=str ,metavar="", required=True, help="Domínio que vamos dar uma olhada")

    #argumento de output 
    parser.add_argument("-o","--output",type=str,metavar="",required=False , help="Manda o output para um arquivo cujo nome vem depois do -o")

    #argumento de security headers
    parser.add_argument("-H","--Headers", action='store_true',required=False,help="Abre os security headers")

    #argumento verbosidade
    parser.add_argument("-v","--verbosity",action='store_true', required=False,help="Informações a mais sobre o script enquanto ele roda")

    #argumento port scan aquatone
    parser.add_argument("-A","--agressive",action='store_true', required=False,help="Aquatone vai meter o louco nas portas")

    return parser.parse_args()




def print_logo():

    print(Fore.YELLOW+ Style.BRIGHT + """ 
        ---------------------------------------------------------------
        db       .d8b.  d88888D db    db       .o88b. d8888b. d888888b 
        88      d8' `8b YP  d8' `8b  d8'      d8P  Y8 88  `8D `~~88~~' 
        88      88ooo88    d8'   `8bd8'       8P      88oobY'    88    
        88      88~~~88   d8'      88         8b      88`8b      88    
        88booo. 88   88  d8' db    88         Y8b  d8 88 `88.    88    
        Y88888P YP   YP d88888P    YP          `Y88P' 88   YD    YP    
        ---------------------------------------------------------------
        -by bruno_carrazza https://github.com/Carrazza?tab=repositories
        ---------------------------------------------------------------
    """)







def crtsh(args):

    start = time.perf_counter()

    #Gets the json response from crt.sh
    json_request = r.get("https://crt.sh/?q=%25."+args.domain+"&output=json")
    
    #json_request2 = r.get("https://crt.sh/?q="+ args.domain + ".%25" + "&output=json")

    #Transforms the response in valid json to be interpreted by python
    json_py = json.loads(json_request.text)
  

    crtsh_set = set()

    #TODO: ok, com certeza tem um jeito menos autista de fazer isso

    for dictionary in json_py:
        
        #print(type(stuff))
        
        #getting the address names 
        addrs_list = dictionary['name_value'].split('\n')
        
        for addrs in addrs_list:

            if addrs not in crtsh_set:
                crtsh_set.add(addrs)


    finish = time.perf_counter()


    if(args.verbosity == True): print(Fore.BLUE+ f"-> crt.sh demorou {round(finish-start,2)} segs")

    return crtsh_set


def sublist3r(args):

    start = time.perf_counter()

    
    sublister = "/home/carrazza/hack/Scripts/Sublist3r/sublist3r.py -d " + args.domain + " -o ./sublister.txt > /dev/null"


    os.system(sublister)

    sublister_set = set()

    #Pegando os domínios do sublister 
    with open("/home/carrazza/hack/Scripts/lazycrt/sublister.txt","r") as f:

        for result in f.readlines():
            
            #quando pegamos o output do sublist3r ele vem com \n, vamos tirar eles
            result = result.replace('\n','')

            if result not in sublister_set:
                sublister_set.add(result)
    

    finish = time.perf_counter()

    if(args.verbosity == True):print(Fore.BLUE+ f"-> Sublist3r demorou {round(finish-start,2)} segs")

    return sublister_set



def unir_resultados(crtsh_set,sublister_set):

    return crtsh_set.union(sublister_set)




def lista_final(list_of_addr):

    print(Fore.BLUE+"-"*50+"Resultados Finais das buscas:"+"-"*50)

    list_of_addr = list(list_of_addr)
    list_of_addr.sort()

    #printa a lista
    for addr in list_of_addr:
        print(Fore.YELLOW + Style.BRIGHT + addr,end="\n")

    print(Fore.BLUE+ "-"*129, end="")
        


def print_arquivo(list_of_addr,args):

    #Printando para um arquivo
    print(Fore.BLUE + "-"*46 + "--->Printando os resultados em " + Fore.CYAN + args.output + Fore.BLUE + "<---"+"-"*46)

    with open(args.output,"w") as f:

        string = "\n".join(list_of_addr)        
        string = string + "\n"
        f.write(string)


def sec_headers(args):

   #Just open the tab lol
   webbrowser.open("https://securityheaders.com/?q="+args.domain+"&followRedirects=on$")
   pass



def aquatone(list_of_addr,args):


    start= time.perf_counter()


    #unindo todos os diretórios pra mandar pro aquatone
    url = " ".join(list_of_addr)


    comand = ""

    if(args.agressive == True): comand = f"mkdir {args.domain};echo {url} | aquatone -ports xlarge -out ./{args.domain} >/dev/null"
    else: comand = f"mkdir {args.domain};echo {url} | aquatone -ports xlarge -out ./{args.domain} >/dev/null"


    os.system(comand)

    finish = time.perf_counter()

    if(args.verbosity == True):print(Fore.BLUE+ f"-> Aquatone demorou {round(finish-start,2)} segs")

    pass


def main():

    #performance time
    start = time.perf_counter()

    args = create_parser()

    #remove trequinhos desnecessários para fazer a request 
    args.domain = args.domain.replace("https://","")
    args.domain = args.domain.replace("www.","")
    args.domain = args.domain.replace("http://","")

    print_logo()

    #Se tiver o parãmetro pedindo pra n usar, don't
    if(args.Headers == True):
        print(Fore.GREEN + "[-] abrindo o scan no security headers")
        #achados do Security Headers
        sec_headers(args)

    #list with all addr
    list_of_addr = set()

    #achados do Crt.sh
    print(Fore.GREEN+"[-] Pesquisando no crt.sh")
    crtsh_set = crtsh(args)

    #achados do Sublist3r
    print(Fore.GREEN+'[-] Pesquisando no Sublist3r')
    sublister_set = sublist3r(args)

    #unindo tudo
    list_of_addr = unir_resultados(crtsh_set,sublister_set)

    #chamando o aquatone
    print(Fore.GREEN+'[-] Pesquisando no Aquatone')
    aquatone(list_of_addr,args)

    #Printa a lista
    lista_final(list_of_addr)

    if (args.output != None): print_arquivo(list_of_addr,args)

    print(Fore.GREEN+"\n[-] Abrindo o report do aquatone")

    sleep(2)

    os.system(f"firefox ./{args.domain}/aquatone_report.html ")
    

    #performance time
    finish = time.perf_counter()


    print(Fore.YELLOW + Style.BRIGHT + f"\nVocê esteve aqui por {round(finish-start,2)} segundos, Obrigado por usar lazycrt!")

    exit()


main()





















